- hosts: server
  remote_user: "{{ username }}"
  become: yes

  vars:
    username: gevorg
    browsers_versions:
      chrome: "128.0"
      firefox: "122.0"

  roles:
    - wiremock_files
    - configuration
    - docker_install
    - docker_compose
