- name: Create browsers.json file
  template:
    src: browsers.json.j2
    dest: /home/{{ username }}/selenoid/grid-router/browsers.json

- name: Copy docker-compose.yml template to remote server
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ username }}/selenoid/docker-compose.yml

- name: Run docker compose file
  shell: docker compose -f /home/{{ username }}/selenoid/docker-compose.yml up -d
  args:
    chdir: "/home/{{ username }}/selenoid"

- name: Check containers state
  shell: docker ps
  register: docker_output

- name: Show running containers
  debug:
    var: docker_output.stdout
