- name: Copy multiple wiremock JSON data files
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ username }}/wiremock/stubs/{{ item }}"
  loop:
    - cource_get_all.json
    - user_get.json
    - user_get_all.json
    - user_soap.json